const events = {
    SIGN_UP: 'SIGN_UP',
    LOG_IN: 'LOG_IN',
    PAGE_VISIT: 'PAGE_VISIT',
    NAVIGATE: 'NAVIGATE',
    REQUEST_CURRENT_LOCATION: 'REQUEST_CURRENT_LOCATION',
    SEARCH: 'SEARCH',
    SHOW_LIKED_MEDIA: 'SHOW_LIKED_MEDIA',
    SHOW_ALL_MEDIA: 'SHOW_ALL_MEDIA',
    CLICK_GALLERY_MEDIA: 'CLICK_GALLERY_MEDIA',
    LIKE_MEDIA: 'LIKE_MEDIA',
    UNLIKE_MEDIA: 'UNLIKE_MEDIA',
    OPEN_MAP: 'OPEN_MAP',
    OPEN_RESTAURANT_PAGE: 'OPEN_RESTAURANT_PAGE',
    OPEN_NOTES: 'OPEN_NOTES',
    CLOSE_NOTES: 'CLOSE_NOTES',
    ADD_NOTE: 'ADD_NOTE',
    EDIT_NOTE: 'EDIT_NOTE',
    DELETE_NOTE: 'DELETE_NOTE',
    ERROR: 'ERROR'
};

export default events;
